NUTRITION_KNOWLEDGE = [
    {
        "id": "cal-targets",
        "title": "Daily Calorie Targets by Goal",
        "tags": ["calories", "cutting", "bulking", "fat loss", "muscle gain", "diet"],
        "content": "Calorie needs depend on goal, bodyweight, and activity level. Fat loss (cutting): Body weight (lbs) × 10–12 = daily calories. Creates a 300–500 kcal deficit. Maintenance (recomp): Body weight (lbs) × 13–15 = daily calories. Supports performance without weight change. Muscle gain (bulking): Body weight (lbs) × 16–18 = daily calories. Lean bulk: +200–300 kcal/day over maintenance. Example: 180 lb athlete cutting = 1800–2160 kcal/day. Bulking = 2880–3240 kcal/day. Track calories for 2 weeks, adjust by 100–200 kcal if weight isn't moving as intended.",
    },
    {
        "id": "macro-ratios",
        "title": "Macronutrient Ratios for Athletes",
        "tags": ["macros", "protein", "carbs", "fat", "muscle gain", "fat loss"],
        "content": "Protein: 0.7–1.0g per lb of bodyweight daily. Essential for muscle repair and growth. Higher end (1g/lb) during caloric deficit or heavy training to preserve muscle. Carbohydrates: Primary fuel for high-intensity exercise. 2–3g/lb for strength athletes, 3–5g/lb for endurance. Fat: Minimum 0.35g/lb/day for hormonal health. Don't drop below 20% of total calories. Muscle gain macro split example (180 lb): 180g protein (720 kcal), 250g carbs (1000 kcal), 70g fat (630 kcal) ≈ 2350 kcal. Fat loss macro split (180 lb at 2000 kcal): 180g protein, 150g carbs, 55g fat.",
    },
    {
        "id": "meal-timing",
        "title": "Meal Timing and Frequency",
        "tags": ["meal timing", "pre-workout", "post-workout", "intermittent fasting", "meal frequency"],
        "content": "Pre-workout (1–2h before): 30–50g carbs + 20–30g protein. Example: rice + chicken, oats + protein shake. Post-workout (within 2h): 40–60g carbs + 30–40g protein to maximize muscle protein synthesis. Meal frequency: 3–5 meals/day. Spreading protein in meals of 25–40g optimizes muscle protein synthesis. Fasting is fine if total daily calories and protein are met. 16:8 intermittent fasting is compatible with muscle gain. Carb backloading: Placing majority of carbs around training enhances performance and body composition. Pre-bed protein: 30–40g casein (cottage cheese, Greek yogurt, casein shake) reduces overnight muscle breakdown.",
    },
    {
        "id": "hydration",
        "title": "Hydration for Performance",
        "tags": ["hydration", "water", "electrolytes", "performance", "caffeine"],
        "content": "Daily baseline: 0.5–0.7 oz per lb of bodyweight. A 180 lb athlete needs 90–126 oz (2.5–3.7L) daily. Add 16–24 oz for every hour of training. Urine color should be pale yellow. Electrolytes matter during sessions >60 min: sodium, potassium, magnesium. Sports drinks or electrolyte tablets. Dehydration of just 2% bodyweight reduces strength by 5–10% and cognition significantly. Caffeine (3–6mg/kg) is an evidence-based ergogenic aid. 1–2 cups of coffee or pre-workout 30–45min before training.",
    },
    {
        "id": "proteins-meat",
        "title": "Animal Protein Sources — Meat",
        "tags": ["protein", "meat", "chicken", "beef", "turkey", "pork", "muscle building", "high protein"],
        "content": "Chicken breast (cooked, 100g): 165 kcal | 31g protein | 3.6g fat | 0g carbs. Lean, versatile. Chicken thigh (cooked, 100g): 209 kcal | 26g protein | 11g fat | 0g carbs. More flavorful, slightly fattier. Turkey breast (cooked, 100g): 157 kcal | 30g protein | 3.2g fat | 0g carbs. Very lean. Lean ground beef 95% (cooked, 100g): 174 kcal | 26g protein | 7.5g fat | 0g carbs. Ground beef 80/20 (cooked, 100g): 254 kcal | 26g protein | 17g fat | 0g carbs. Higher calorie. Beef sirloin steak (cooked, 100g): 207 kcal | 27g protein | 11g fat | 0g carbs. Flank steak (cooked, 100g): 192 kcal | 28g protein | 8.5g fat | 0g carbs. Lean, high protein. Pork tenderloin (cooked, 100g): 143 kcal | 26g protein | 3.5g fat | 0g carbs. Very lean pork. Bison (cooked, 100g): 143 kcal | 28g protein | 3.3g fat | 0g carbs. Very lean, high iron. Venison/deer (cooked, 100g): 158 kcal | 30g protein | 3.2g fat | 0g carbs.",
    },
    {
        "id": "proteins-fish",
        "title": "Fish and Seafood Protein Sources",
        "tags": ["protein", "fish", "seafood", "salmon", "tuna", "omega-3", "lean protein", "muscle building"],
        "content": "Salmon (cooked, 100g): 208 kcal | 28g protein | 10g fat | 0g carbs. Omega-3 rich (~2.3g EPA/DHA). Tilapia (cooked, 100g): 128 kcal | 26g protein | 2.7g fat | 0g carbs. Very lean, mild flavor. Cod (cooked, 100g): 105 kcal | 23g protein | 0.9g fat | 0g carbs. Extremely lean. Tuna (canned in water, 100g): 116 kcal | 25.5g protein | 0.8g fat | 0g carbs. Convenient high protein. Sardines (canned in oil, 100g): 208 kcal | 25g protein | 11.5g fat | 0g carbs. Rich in omega-3 and calcium. Shrimp (cooked, 100g): 99 kcal | 24g protein | 0.3g fat | 0.2g carbs. Very lean. Halibut (cooked, 100g): 140 kcal | 27g protein | 2.9g fat | 0g carbs. Trout (cooked, 100g): 190 kcal | 26g protein | 8.5g fat | 0g carbs. Omega-3 rich. Scallops (cooked, 100g): 111 kcal | 20g protein | 1.2g fat | 5g carbs.",
    },
    {
        "id": "proteins-eggs-dairy",
        "title": "Eggs and Dairy Protein Sources",
        "tags": ["protein", "eggs", "dairy", "Greek yogurt", "cottage cheese", "whey", "casein", "muscle building"],
        "content": "Whole egg (1 large, 50g): 78 kcal | 6g protein | 5g fat | 0.6g carbs. Complete amino acid profile. Egg whites (100g): 52 kcal | 11g protein | 0.2g fat | 0.7g carbs. Pure protein, low calorie. Greek yogurt, non-fat (100g): 59 kcal | 10g protein | 0.4g fat | 3.6g carbs. Probiotic, high protein. Cottage cheese, low fat (100g): 84 kcal | 12g protein | 2.3g fat | 3.4g carbs. High casein, slow digesting. Milk, whole (240ml): 149 kcal | 8g protein | 8g fat | 12g carbs. Cheddar cheese (100g): 403 kcal | 25g protein | 33g fat | 1.3g carbs. Calorie dense. Mozzarella (100g): 280 kcal | 28g protein | 17g fat | 3.1g carbs. Whey protein powder (30g serving): ~120 kcal | 24g protein | 1.5g fat | 3g carbs. Fast absorbing post-workout. Casein protein powder (30g serving): ~120 kcal | 24g protein | 1g fat | 4g carbs. Slow digesting, good pre-bed.",
    },
    {
        "id": "proteins-plant",
        "title": "Plant-Based Protein Sources (Vegetarian and Vegan)",
        "tags": ["plant protein", "vegetarian", "vegan", "tofu", "lentils", "beans", "tempeh", "protein"],
        "content": "Tofu, firm (100g): 76 kcal | 8g protein | 4.5g fat | 1.9g carbs. Complete protein. Absorbs flavor. Tempeh (100g): 193 kcal | 19g protein | 11g fat | 9g carbs. Fermented, high protein, gut-friendly. Edamame (100g): 121 kcal | 11g protein | 5g fat | 8.9g carbs. Complete protein, fiber rich. Lentils, cooked (100g): 116 kcal | 9g protein | 0.4g fat | 20g carbs. High fiber, iron. Black beans, cooked (100g): 132 kcal | 8.9g protein | 0.5g fat | 24g carbs. Chickpeas, cooked (100g): 164 kcal | 8.9g protein | 2.6g fat | 27g carbs. Versatile, high fiber. Seitan (100g): 370 kcal | 75g protein | 1.9g fat | 14g carbs. Highest plant protein source. NOT gluten-free. Hemp seeds (30g): 166 kcal | 9.5g protein | 15g fat | 2.6g carbs. Complete protein, omega-3. Pea protein powder (30g serving): ~120 kcal | 24g protein | 2g fat | 2g carbs. Great BCAA profile. Nutritional yeast (15g): 45 kcal | 5g protein | 0.5g fat | 4g carbs. B12 fortified, cheesy flavor. Quinoa (cooked, 100g): 120 kcal | 4.4g protein | 1.9g fat | 21g carbs. Complete protein grain.",
    },
    {
        "id": "carbs-grains",
        "title": "Grain and Starch Carbohydrate Sources",
        "tags": ["carbs", "rice", "oats", "potato", "bread", "pasta", "grains", "energy", "carbohydrates"],
        "content": "White rice, cooked (100g): 130 kcal | 2.7g protein | 0.3g fat | 28g carbs. Fast digesting, great post-workout. Brown rice, cooked (100g): 112 kcal | 2.6g protein | 0.9g fat | 23g carbs. More fiber, slower digesting. Oats, rolled dry (100g): 389 kcal | 17g protein | 7g fat | 66g carbs. High fiber, beta-glucan. White potato, baked (100g): 93 kcal | 2.5g protein | 0.1g fat | 21g carbs. High potassium. Sweet potato, baked (100g): 103 kcal | 2.3g protein | 0.1g fat | 24g carbs. Beta-carotene rich. Pasta (cooked, 100g): 131 kcal | 5g protein | 1.1g fat | 25g carbs. Versatile carb source. Whole wheat pasta (cooked, 100g): 124 kcal | 5.3g protein | 1.1g fat | 24g carbs. Quinoa (cooked, 100g): 120 kcal | 4.4g protein | 1.9g fat | 21g carbs. Complete protein.",
    },
    {
        "id": "carbs-fruit",
        "title": "Fruit Sources of Carbohydrates",
        "tags": ["fruit", "carbs", "banana", "berries", "pre-workout", "antioxidants", "carbohydrates"],
        "content": "Banana (medium, 118g): 105 kcal | 1.3g protein | 0.4g fat | 27g carbs. Fast carbs, potassium. Apple (medium, 182g): 95 kcal | 0.5g protein | 0.3g fat | 25g carbs. High fiber. Blueberries (100g): 57 kcal | 0.7g protein | 0.3g fat | 14g carbs. High antioxidants. Strawberries (100g): 32 kcal | 0.7g protein | 0.3g fat | 7.7g carbs. Low calorie, high vitamin C. Mango (100g): 60 kcal | 0.8g protein | 0.4g fat | 15g carbs. High sugar, great pre-workout. Dates (100g): 282 kcal | 2.5g protein | 0.4g fat | 75g carbs. Dense fast carbs, great pre-workout. Tart cherries (100g): 50 kcal | 1g protein | 0.3g fat | 12g carbs. Reduces muscle soreness.",
    },
    {
        "id": "healthy-fats",
        "title": "Healthy Fat Sources for Athletes",
        "tags": ["fat", "healthy fats", "nuts", "avocado", "olive oil", "omega-3", "seeds", "testosterone"],
        "content": "Avocado (100g): 160 kcal | 2g protein | 15g fat | 9g carbs (7g fiber). Potassium, monounsaturated fat. Almonds (30g): 173 kcal | 6g protein | 15g fat | 6g carbs. Vitamin E, magnesium. Walnuts (30g): 185 kcal | 4.3g protein | 18.5g fat | 3.9g carbs. Highest omega-3 of any nut. Peanut butter (2 tbsp, 32g): 188 kcal | 8g protein | 16g fat | 6g carbs. Easy calories. Olive oil (1 tbsp, 14g): 119 kcal | 0g protein | 13.5g fat | 0g carbs. Heart-healthy, monounsaturated. Chia seeds (1 tbsp, 12g): 58 kcal | 2g protein | 3.7g fat | 5g carbs. Omega-3, fiber. Hemp seeds (3 tbsp, 30g): 166 kcal | 9.5g protein | 15g fat | 2.6g carbs. Complete protein + omega-3. Dark chocolate 70%+ (30g): 170 kcal | 2.1g protein | 12g fat | 13g carbs. Antioxidants, magnesium.",
    },
    {
        "id": "vegetables-high-volume",
        "title": "Vegetables — High Volume, Low Calorie",
        "tags": ["vegetables", "low calorie", "high volume", "cutting", "fiber", "micronutrients", "fat loss"],
        "content": "Spinach (100g): 23 kcal | 2.9g protein | 0.4g fat | 3.6g carbs. Iron, folate, nitrates for performance. Kale (100g): 49 kcal | 4.3g protein | 0.9g fat | 9g carbs. Calcium, vitamin K. Broccoli (100g): 34 kcal | 2.8g protein | 0.4g fat | 7g carbs. High fiber, vitamin C. Zucchini (100g): 17 kcal | 1.2g protein | 0.3g fat | 3.1g carbs. Very low calorie volume food. Cucumber (100g): 16 kcal | 0.7g protein | 0.1g fat | 3.6g carbs. Mostly water, very low calorie. Bell pepper (100g): 31 kcal | 1g protein | 0.3g fat | 6g carbs. Highest vitamin C of any vegetable. Mushrooms (100g): 22 kcal | 3.1g protein | 0.3g fat | 3.3g carbs. Vitamin D, immune support. Asparagus (100g): 20 kcal | 2.2g protein | 0.1g fat | 3.9g carbs. Natural diuretic, folate.",
    },
    {
        "id": "vegetarian-diet-plan",
        "title": "Vegetarian Athlete Nutrition Plan",
        "tags": ["vegetarian", "diet plan", "plant protein", "meal plan", "muscle building", "sample diet"],
        "content": "Vegetarian athletes can absolutely build muscle and perform at high levels with smart planning. Key challenge: Getting enough complete protein and sufficient calories. Protein strategy: Combine rice + beans (complete amino acid profile), eat eggs and dairy, use protein powders. Top vegetarian protein sources (daily staples): Greek yogurt, cottage cheese, eggs, tofu, tempeh, edamame, lentils, chickpeas. Sample 2400 kcal vegetarian muscle-building day: Breakfast: 3 scrambled eggs + oats with protein powder + banana = ~700 kcal, 50g protein. Lunch: Lentil + rice bowl + spinach salad + feta = ~600 kcal, 35g protein. Snack: Greek yogurt + almonds + berries = ~350 kcal, 20g protein. Dinner: Tofu stir-fry + brown rice + broccoli = ~600 kcal, 35g protein. Evening: Cottage cheese + peanut butter = ~300 kcal, 25g protein. Total: ~2550 kcal, ~165g protein. Micronutrients to monitor: Iron (eat with vitamin C), B12 (eggs/dairy cover it), zinc (pumpkin seeds), calcium (dairy/fortified foods), omega-3 (hemp/flax/chia or algae supplement).",
    },
    {
        "id": "vegan-diet-plan",
        "title": "Vegan Athlete Nutrition Plan",
        "tags": ["vegan", "diet plan", "plant protein", "meal plan", "supplements", "B12", "muscle building"],
        "content": "Vegan athletes can build muscle and compete at high levels with strategic planning. Protein priority: Aim for 0.8–1g/lb bodyweight using diverse plant sources throughout the day. Best vegan protein sources: Seitan, tempeh, tofu, edamame, lentils, black beans, chickpeas, pea protein, hemp seeds. Sample 2500 kcal vegan muscle-building day (180 lb athlete): Breakfast: Pea protein smoothie + oats + banana + nut butter = ~750 kcal, 45g protein. Lunch: Tempeh + quinoa + roasted vegetables = ~650 kcal, 40g protein. Snack: Edamame + rice cakes + hummus = ~400 kcal, 20g protein. Dinner: Lentil + black bean curry + brown rice + kale = ~600 kcal, 35g protein. Evening: Hemp seeds + dates + almond butter = ~400 kcal, 15g protein. Total: ~2800 kcal, ~155g protein. Supplements essential: B12 (no vegan food source), Vitamin D3 (algae-based), omega-3 (algae oil), creatine (especially important — only found in animal products).",
    },
    {
        "id": "omnivore-diet-plan",
        "title": "Omnivore Athlete Nutrition Plan",
        "tags": ["omnivore", "diet plan", "meal plan", "muscle building", "fat loss", "chicken", "sample diet"],
        "content": "Omnivore athletes have the most flexible options for hitting protein and calorie targets. Sample 2800 kcal muscle-building day (180 lb athlete, ~1g protein/lb): Breakfast: 4 whole eggs + 2 slices whole wheat toast + orange juice = ~550 kcal, 32g protein. Mid-morning: Greek yogurt + berries + granola = ~400 kcal, 20g protein. Lunch: 200g chicken breast + 200g white rice + broccoli + olive oil = ~700 kcal, 55g protein. Pre-workout snack: Banana + whey protein shake = ~280 kcal, 28g protein. Dinner: 200g salmon + sweet potato + asparagus = ~600 kcal, 45g protein. Evening: Cottage cheese + walnuts = ~300 kcal, 25g protein. Total: ~2830 kcal, ~205g protein. For fat loss (target 2200 kcal, 180g protein): Reduce rice portions by half, use leaner cuts, swap dinner to tilapia + vegetables only.",
    },
    {
        "id": "high-protein-fat-loss",
        "title": "High Protein Fat Loss Diet Strategy",
        "tags": ["fat loss", "cutting", "high protein", "diet", "caloric deficit", "volume eating", "satiety"],
        "content": "Fat loss requires a caloric deficit, but protein must stay high to preserve muscle. Target: 1g protein per lb bodyweight, deficit of 300–500 kcal/day. High-satiety, low-calorie foods to prioritize: egg whites, chicken breast, white fish (cod, tilapia), shrimp, Greek yogurt, cottage cheese, vegetables, whey protein. Volume eating strategy: Fill half the plate with non-starchy vegetables (broccoli, spinach, zucchini, cucumber — ~30 kcal per cup). Hunger management: Eat protein at every meal (keeps you full), drink water before meals, use soup/salads as starters. Foods to moderate (calorie dense): nuts, oils, cheese, dried fruit, sauces, alcohol. Avoid liquid calories: juices, sodas, alcohol. Exception: protein shakes. Diet breaks: After 8–12 weeks of deficit, a 1–2 week maintenance refeed can restore leptin, performance, and adherence.",
    },
    {
        "id": "muscle-gain-diet",
        "title": "Muscle Gain Diet Strategy",
        "tags": ["muscle gain", "bulking", "caloric surplus", "diet", "mass gaining", "lean bulk", "dirty bulk"],
        "content": "Muscle gain requires a caloric surplus with high protein intake. Lean bulk: 200–300 kcal over maintenance. Protein: 0.8–1g/lb bodyweight. Spread across 4–5 meals of 30–50g each. Calorie-dense, nutrient-rich foods for gaining: oats, rice, pasta, whole eggs, full-fat dairy, nut butters, avocados, lean meat in large portions, protein shakes with milk. Bulking meal example (600–700 kcal): 250g ground beef + 200g rice + avocado + olive oil drizzle. Mass gainer smoothie (800+ kcal): 2 cups whole milk + 2 bananas + 2 tbsp peanut butter + 1 cup oats + 1 scoop protein powder. Lean bulk (+200–300 kcal) adds muscle with minimal fat gain. Sleep is anabolic: 7–9 hours per night. Growth hormone peaks during deep sleep.",
    },
    {
        "id": "pre-post-workout-nutrition",
        "title": "Pre and Post Workout Nutrition",
        "tags": ["pre-workout", "post-workout", "nutrition timing", "muscle gain", "performance", "carbs", "protein"],
        "content": "Pre-workout (60–90 min before training): Goal: Fuel performance, prevent muscle breakdown. Ideal: 30–50g carbs + 20–30g protein + low fiber/fat (for fast digestion). Examples: Chicken + white rice, oatmeal + protein shake, banana + Greek yogurt, rice cakes + peanut butter + whey. Immediate pre-workout (15–30 min): Simple carbs only if needed. Banana, dates, gels, sports drink. Post-workout (within 30–60 min): Goal: Replenish glycogen, stimulate muscle protein synthesis (MPS). Ideal: 40–60g carbs + 30–40g protein. Examples: Chicken + rice, salmon + sweet potato, protein shake + banana + milk, Greek yogurt + oats. The anabolic window is wider than thought — eating within 2 hours is fine. Total daily nutrition matters more. Intra-workout (for sessions >75 min): 30–60g fast carbs per hour (gels, sports drink, banana).",
    },
    {
        "id": "supplements-nutrition",
        "title": "Evidence-Based Supplements for Athletes",
        "tags": ["supplements", "creatine", "whey protein", "caffeine", "vitamin D", "fish oil", "omega-3", "performance"],
        "content": "Grade A evidence (proven, safe): 1. Creatine monohydrate: 3–5g/day. Increases strength, power, and muscle mass. Cheap and extremely safe. Take daily regardless of training day. 2. Whey protein: 20–40g post-workout or to hit daily protein goals. Complete amino acid profile. 3. Caffeine: 3–6mg/kg 30–45min pre-workout. Improves strength, endurance, focus. Tolerance builds; cycle off periodically. 4. Vitamin D3: 2000–4000 IU/day with fat. Most people are deficient. Critical for testosterone, bone health, immunity. 5. Fish oil/Omega-3: 2–3g EPA+DHA/day. Reduces inflammation, supports heart and joint health. Grade B evidence (likely useful): Beta-alanine: 3.2–6.4g/day. Reduces muscle burn in 60–240 sec work. Magnesium glycinate: 200–400mg before bed. Improves sleep, reduces cramps. Skip: Proprietary blends, fat burners, most pre-workout complexes (caffeine + creatine is 90% of the benefit).",
    },
    {
        "id": "diet-for-endurance",
        "title": "Nutrition for Endurance Athletes",
        "tags": ["endurance", "running", "cycling", "carbs", "carb loading", "race nutrition", "glycogen", "marathon"],
        "content": "Endurance sports (running, cycling, swimming) require higher carbohydrate intake than strength sports. Daily carbs: 5–10g/kg bodyweight depending on training volume. A 70kg runner doing 60km/week needs 350–700g carbs/day. Protein: 1.2–1.6g/kg/day. Slightly lower than strength athletes but still critical for muscle repair. Fat: 20–35% of calories. Pre-race fueling: High carb meal (pasta, rice, bread) 3–4 hours before. Low fiber, low fat, moderate protein. During race/long session (>75 min): 30–60g carbs/hour. Gels, dates, bananas, sports drink. Post-endurance recovery: Carbs + protein within 30 min. Chocolate milk is a surprisingly effective recovery drink (carb:protein ratio 4:1). Carb loading (before race >2h): 3 days of 10g carbs/kg/day, reduce training.",
    },
    {
        "id": "diet-for-athletes-recovery",
        "title": "Recovery Nutrition and Anti-Inflammatory Foods",
        "tags": ["recovery", "anti-inflammatory", "soreness", "DOMS", "sleep", "tart cherry", "collagen", "muscle repair"],
        "content": "Recovery nutrition reduces muscle soreness and speeds return to performance. Within 30 min post-workout: 30–40g protein + 40–60g carbs. Stimulates MPS and glycogen replenishment. Anti-inflammatory foods to include regularly: fatty fish (salmon, sardines, mackerel), tart cherries, turmeric + black pepper, ginger, berries, dark leafy greens, olive oil, walnuts. Tart cherry juice (240ml twice daily): Shown to reduce DOMS by up to 25% and improve sleep quality. Glycine (from collagen/bone broth): 5–10g before sleep + vitamin C. Supports tendon and ligament recovery. Alcohol impairs muscle protein synthesis and sleep quality — limit to 1–2 drinks max on rest days. Sleep optimization: The most underrated recovery tool. 7–9 hours. Keep room cool (65–67°F), dark, and consistent schedule.",
    },
]
